apiVersion: skaffold/v4beta9
kind: Config
metadata:
  name: jazz-records
build:
  artifacts:
    - image: jazz-records
      docker:
        dockerfile: Dockerfile
    - image: jazz-records-init
      docker:
        dockerfile: k8s/init/Dockerfile
    - image: jazz-records-migrations
      docker:
        dockerfile: k8s/migration/Dockerfile
manifests:
  rawYaml:
  - k8s/*.yaml
deploy:
  kubectl: {}
