apiVersion: apps/v1
kind: Deployment
metadata:
  name: jazz-records-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jazz-records
  template:
    metadata:
      labels:
        app: jazz-records
    spec:
      initContainers:
        - name: jazz-records-init
          image: jazz-records-init:v0.1.0
      containers:
        - name: jazz-records
          image: jazz-records:v0.1.0
          imagePullPolicy: IfNotPresent
          envFrom:
          - secretRef:
              name: jazz-records-secret
          - configMapRef:
              name: jazz-records-config
          ports:
          - containerPort: 8080
